# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  ####################### REQUIRED ######################################
  ## FOR TINY HOME Workload Identity Federation
  WORKLOAD_IDENTITY_POOL: test-identity-pool


jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
  
    strategy:
      matrix:
        project: [imposing-timer-420716]
        include:
          - project: imposing-timer-420716
            gcp_project_number: 645586971453
      
    runs-on: ubuntu-latest

    outputs:
      ### REQUIRED ###
      GCP_PROJECT: ${{ steps.output-variables.outputs.GCP_PROJECT }}

    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
  
    - id: 'auth' 
      name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'https://iam.googleapis.com/projects/645586971453/locations/global/workloadIdentityPools/test-identity-pool/providers/test-identity-provider'
        service_account: 'test-service-account@imposing-timer-420716.iam.gserviceaccount.com'
      
       
   
    - name: Access Token 
      run: |
          echo ${{steps.auth.outputs.access_token}}
          echo GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS"
          cat $GOOGLE_APPLICATION_CREDENTIALS
          echo ${{steps.auth.outputs.project_id}}
          echo ${{steps.auth.outputs.credentials_file_path}}
          echo ${{steps.auth.outputs.auth_token}}
        
    - name: Run API integration tests
      run: |
        mvn test -Dcucumber.features = 'src/test/java/com/ww/step_definitions/FindStudio_StepDefinitions.java'
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
